version: '3.8'

services:
  # Seed node - first node in the network
  seed-node:
    build: .
    container_name: zion-seed
    environment:
      - ZION_MODE=seed
      - ZION_LOG_LEVEL=info
    volumes:
      - seed-data:/home/zion/.zion
    ports:
      - "18081:18081"  # P2P port
      - "18080:18080"  # RPC port
    networks:
      - zion-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Pool server
  pool-server:
    build: .
    container_name: zion-pool
    environment:
      - ZION_MODE=pool
      - POOL_PORT=3333
      - POOL_DIFFICULTY=1000
      - POOL_FEE=1
      - SEED_NODES="seed-node:18081"
      - ZION_LOG_LEVEL=info
    volumes:
      - pool-data:/home/zion/.zion
    ports:
      - "3333:3333"    # Pool stratum port
      - "28080:18080"  # RPC port (mapped to different host port)
      - "28081:18081"  # P2P port (mapped to different host port)
    networks:
      - zion-network
    depends_on:
      - seed-node
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Miner (optional - comment out if not needed)
  miner:
    build: .
    container_name: zion-miner
    environment:
      - ZION_MODE=miner
      - MINER_POOL=pool-server:3333
      - MINER_THREADS=4
      - MINER_WALLET=YOUR_WALLET_ADDRESS_HERE  # Replace with actual wallet
    networks:
      - zion-network
    depends_on:
      - pool-server
    restart: unless-stopped
    profiles:
      - mining  # Only starts when --profile mining is specified

  # Additional full node (optional)
  full-node:
    build: .
    container_name: zion-node
    environment:
      - ZION_MODE=daemon
      - SEED_NODES="seed-node:18081"
      - ZION_LOG_LEVEL=info
    volumes:
      - node-data:/home/zion/.zion
    ports:
      - "38080:18080"  # RPC port (mapped to different host port)
      - "38081:18081"  # P2P port (mapped to different host port)
    networks:
      - zion-network
    depends_on:
      - seed-node
    restart: unless-stopped
    profiles:
      - full  # Only starts when --profile full is specified

volumes:
  seed-data:
    driver: local
  pool-data:
    driver: local
  node-data:
    driver: local

networks:
  zion-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16