version: "3.8"

services:
  zion-node:
    build:
      context: .
      dockerfile: docker/Dockerfile.zion-cryptonote.minimal
    image: zion:production-fixed
    container_name: zion-production
    restart: unless-stopped
    ports:
      - "18080:18080"  # P2P
      - "18081:18081"  # RPC
      - "8070:8070"    # Wallet daemon
    volumes:
      - zion_data:/home/zion/.zion
      - ./logs:/var/log/zion
    environment:
      - ZION_LOG_LEVEL=info
    command: [
      "/usr/local/bin/ziond",
      "--data-dir", "/home/zion/.zion",
      "--p2p-bind-port", "18080",
      "--rpc-bind-port", "18081",
      "--rpc-bind-ip", "0.0.0.0",
      "--log-level", "2"
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  # Pool server (optional - uncomment to run pool)
  zion-pool:
    build:
      context: .
      dockerfile: docker/Dockerfile.zion-cryptonote.prod
    image: zion:production-fixed
    container_name: zion-pool
    restart: unless-stopped
    ports:
      - "3333:3333"    # Stratum pool
    volumes:
      - zion_pool_data:/home/zion/.zion
      - ./logs:/var/log/zion
    environment:
      - ZION_MODE=pool
      - POOL_PORT=3333
      - POOL_DIFFICULTY=1000
      - POOL_FEE=1
    command: [
      "/usr/local/bin/ziond",
      "--data-dir", "/home/zion/.zion",
      "--pool-mode",
      "--pool-port", "3333",
      "--pool-bind-ip", "0.0.0.0"
    ]
    depends_on:
      - zion-node
    profiles:
      - pool
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

volumes:
  zion_data:
    driver: local
  zion_pool_data:
    driver: local

networks:
  default:
    name: zion-network
    driver: bridge
