version: "3.8"

networks:
  zion-seeds:
    name: zion-seeds
    driver: bridge
    external: true

services:
  seed1:
    image: zion:production-fixed
    container_name: zion-seed1
    restart: unless-stopped
    environment:
      - ZION_MODE=daemon
      - ZION_LOG_LEVEL=info
      - P2P_PORT=18080
      - RPC_PORT=18081
    volumes:
      - seed1-data:/home/zion/.zion
    networks:
      - zion-seeds

  seed2:
    image: zion:production-fixed
    container_name: zion-seed2
    restart: unless-stopped
    environment:
      - ZION_MODE=daemon
      - ZION_LOG_LEVEL=info
      - P2P_PORT=18080
      - RPC_PORT=18081
    volumes:
      - seed2-data:/home/zion/.zion
    depends_on:
      - seed1
    networks:
      - zion-seeds

  pool:
    image: zion:pool-latest
    container_name: zion-pool
    restart: unless-stopped
    user: "0:0"  # start as root; entrypoint will chown and drop to 'zion' via gosu
    environment:
      - ZION_MODE=daemon
      - ZION_LOG_LEVEL=info
    volumes:
      - pool-data:/home/zion/.zion
    depends_on:
      - seed1
      - seed2
    networks:
      - zion-seeds

  pool-nodejs:
    build:
      context: ../pool
      dockerfile: Dockerfile
    image: zion:pool-nodejs
    container_name: zion-pool-nodejs
    restart: unless-stopped
    environment:
      - POOL_PORT=3333
      - POOL_BIND=0.0.0.0
    # Port 3333 přebírá Uzi-Pool; stub ponecháváme bez public portu
    networks:
      - zion-seeds

  rpc-shim:
    build:
      context: ../adapters/zion-rpc-shim
      dockerfile: Dockerfile
    image: zion:rpc-shim
    container_name: zion-rpc-shim
    restart: unless-stopped
    environment:
      - SHIM_PORT=18089
      - ZION_RPC_URL=http://seed1:18081/json_rpc
    ports:
      - "18089:18089"  # Monero-like JSON-RPC endpoint for external pool software
    depends_on:
      - seed1
    networks:
      - zion-seeds

  uzi-pool:
    image: zion:uzi-pool
    container_name: zion-uzi-pool
    restart: unless-stopped
    environment:
      - POOL_CONFIG=/config/config.json
    volumes:
      - ../adapters/uzi-pool-config:/config:ro
    depends_on:
      - redis
      - rpc-shim
    ports:
      - "3333:3333"
    networks:
      - zion-seeds

  redis:
    image: redis:6-alpine
    container_name: zion-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "no"]
    networks:
      - zion-seeds

volumes:
  seed1-data:
    driver: local
  seed2-data:
    driver: local
  pool-data:
    driver: local
