version: "3.8"

networks:
  zion-seeds:
    external: true
    name: zion-seeds

services:
  xmrig-test:
    image: xmrig/xmrig:latest
    container_name: zion-xmrig-test
    restart: unless-stopped
    command:
      ["--url","stratum+tcp://91.98.122.165:3333",
       "--algo","rx/0",
       "--user","Z7v1oJtV3pQAYt2oR9wA3sL5xTnQmBkR6yU8iN2mK4hP9eD3cF7aJ1kL2pQ9wE7rT6",
       "--pass","x",
       "--keepalive",
       "--rig-id","TEST",
       "--print-time","5",
       "--donate-level","0"]
    # Run outside the zion-seeds network, connect directly to host IP.
    # This avoids DNS/service discovery dependencies during testing.
